### ISSUE TITLE
Animation improvements

### ISSUE THREAD

**Issue by 66BA9Q-ME49** [Anoms12/Advanced-Tab-Groups#11]
Zen version: 1.7.5t
Advanced Tab Groups version: Firefox 135 (Twilight, recommended), commit [1e7e4c8](https://github.com/Anoms12/Advanced-Tab-Groups/commit/1e7e4c8398da55f609715169db6c6ca7ce9f2591)
## 1. The group collapsing animation is very slow
This hurts productivity a lot because I need to wait for the group to collapse before going to another tab because the tab list is shifted up when the group collapses.

## 2. The group opening animation ends abruptly
On the contrary, the collapsing animation has a smooth ending.

## 3. Tabs inside groups are not styled like normal Zen tabs
- Normal Zen tabs have a smooth scale-down animation when clicked, whereas tabs contained in groups are just scaled down on click, without animation.
- The text inside normal Zen tabs is still sharp when the tab is scaled down, but the text in grouped tabs becomes blurry.
- Normal Zen tabs have a background blur effect visible when moving the tabs, but grouped tabs are just transparent

## Video

https://github.com/user-attachments/assets/54b82306-50e5-4681-9c36-8d371932a18a

## Used CSS
userChrome.css
```css
@import url("tab-group.css");
@import url("pip-rounded-corners.css");
```
`tab-group.css` is the css file directly downloaded from your repo
`pip-rounded-corners.css` is from [ghostsshadow/zen-pip-rounded-corners](https://github.com/ghostsshadow/zen-pip-rounded-corners)
```css
@-moz-document url("chrome://global/content/pictureinpicture/player.xhtml")
{
  html {
    border: 0px solid rgba(255, 0, 0, 255) !important;
    border-radius: 1rem !important;
  }
}
```
