### ISSUE TITLE
No way to scroll in tab group because of 6c64684

### ISSUE THREAD

**Issue by NickCoolberg** [Anoms12/Advanced-Tab-Groups#22]
Hello

I hope you're doing well and thank you for your excellent work!

A few hours ago, I updated the configuration and ran into a problem:
If the ["overflow-y" property is set to "hidden"](https://github.com/Anoms12/Advanced-Tab-Groups/commit/6c6468478a7f2437e08605f2c12baa66a1dedff8#diff-cec334b35372a6263831c0dbb4db7c618b453ecf53188d1e406d941f2902f925R315) scrolling in the tab group is not possible.

I guess the reason for this fix may be in the animation of the group opening, but I don't see any visual problems if I set the value to "auto".

Can you suggest or better show me what the original problem looks like so that I can work on a solution that at the same time fixes it and leaves scrolling if the tab height goes beyond 500px?

**Comment by Anoms12** [comment]
@NickCoolberg On the original PR the video showed a scrollbar that would grow as the tab group expanded, this small change hid that scrollbar. I used 500px as a temporary fix to an animation flaw cause by a twilight update. A PR would be appreciated as myself and @Ender-Wang are currently fixing on other issues from https://github.com/Anoms12/Advanced-Tab-Groups/discussions/19

**Comment by Ender-Wang** [comment]
Sorry about that; I did not notice there was a height limit when I removed the scrollable property. 
It's actually about [the scroll bar showing and then hiding itself quickly when expanding a group](https://github.com/Anoms12/Advanced-Tab-Groups/discussions/19#discussioncomment-12240845), which causes a glitch feeling, the max height value is two lines above where I changed to hide the y-axis overflow. If you do not mind the scrollbar flashing and wanna have a scrollable tab group, you can replace this:
```css
/* Expand when NOT collapsed */
&:not([collapsed]) {
  max-height: 500px !important;
  padding-top: 0;
  overflow-y: hidden !important;
}
```
by
```css
/* Expand when NOT collapsed */
&:not([collapsed]) {
  padding-top: 0;
  overflow-y: auto !important;
}
```
